[font]
size = 11.0

[font.normal]
family = "HackNerdFont"
style = "Regular"

[font.bold]
family = "HackNerdFont"
style = "Bold"

[font.italic]
family = "HackNerdFont"
style = "Italic"

[font.bold_italic]
family = "HackNerdFont"
style = "Bold Italic"

[colors.primary]
foreground = "#ffffff"
background = "#000000"
